baseurl: ""

# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           blog/:year/:month/:day/:title/
#relative_permalinks: true

# Setup
title:               Ali Borhani
tagline:             'گاه‌نوشته‌های یک توسعه‌دهنده!'
description:         'علی برهانی
<br>
گاه‌نوشته‌های یک توسعه‌دهنده!'
url:                 http://aliborhani.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Ali Borhani
  url:               https://twitter.com/aliborhani1
  email:             aliborhani1@gmail.com

# Custom vars
version:             1.0.0

gems: [jekyll-paginate]
